# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cache.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61\x63he.proto\x12\x06\x61verse\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"D\n\x11SetWithTTLRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x13\n\x0bttl_seconds\x18\x03 \x01(\x03\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\r\n\x0b\x44umpRequest\"\x1f\n\x0c\x44umpResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x98\x02\n\x0c\x43\x61\x63heService\x12.\n\x03Get\x12\x12.averse.GetRequest\x1a\x13.averse.GetResponse\x12.\n\x03Set\x12\x12.averse.SetRequest\x1a\x13.averse.SetResponse\x12<\n\nSetWithTTL\x12\x19.averse.SetWithTTLRequest\x1a\x13.averse.SetResponse\x12\x37\n\x06\x44\x65lete\x12\x15.averse.DeleteRequest\x1a\x16.averse.DeleteResponse\x12\x31\n\x04\x44ump\x12\x13.averse.DumpRequest\x1a\x14.averse.DumpResponseB\x0cZ\n../cachepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n../cachepb'
  _globals['_GETREQUEST']._serialized_start=23
  _globals['_GETREQUEST']._serialized_end=48
  _globals['_GETRESPONSE']._serialized_start=50
  _globals['_GETRESPONSE']._serialized_end=93
  _globals['_SETREQUEST']._serialized_start=95
  _globals['_SETREQUEST']._serialized_end=135
  _globals['_SETWITHTTLREQUEST']._serialized_start=137
  _globals['_SETWITHTTLREQUEST']._serialized_end=205
  _globals['_SETRESPONSE']._serialized_start=207
  _globals['_SETRESPONSE']._serialized_end=237
  _globals['_DELETEREQUEST']._serialized_start=239
  _globals['_DELETEREQUEST']._serialized_end=267
  _globals['_DELETERESPONSE']._serialized_start=269
  _globals['_DELETERESPONSE']._serialized_end=302
  _globals['_DUMPREQUEST']._serialized_start=304
  _globals['_DUMPREQUEST']._serialized_end=317
  _globals['_DUMPRESPONSE']._serialized_start=319
  _globals['_DUMPRESPONSE']._serialized_end=350
  _globals['_CACHESERVICE']._serialized_start=353
  _globals['_CACHESERVICE']._serialized_end=633
# @@protoc_insertion_point(module_scope)
